### PR TITLE
update to newest gradle

### PR DESCRIPTION
**Pull request by Dream-Master**
bs+sa+deps etc

### CODE REVIEW

**Review by Ethryan — COMMENTED** [review]
26 thousand edits, my pad screams in pain when I try and look at it.

**Comment by Dream-Master** [comment]
spotless mostly. But i guess some mor stuff was changed. a few classes missing.

**Comment by mitchej123** [comment]
Can we do this PR without spotless?

It's going to ruin the ability compare easily with agricraft, and it's going to destroy the WIP PR if we decide to run with that.

**Comment by bombcar** [comment]
Can you revert dreams commit? Otherwise I can reapply my changes or just work against the main pr

**Comment by mitchej123** [comment]
My guess is it would be easier to reapply your commits, ensuring disable spotless is in, than to revert his

**Comment by bombcar** [comment]
closed in favor of https://github.com/GTNewHorizons/CropsNH/pull/3

**Pull request closed without merging**
